FROM rust:1.67.0-slim as builder

#TARGETOS - OS component from --platform, e.g. linux
#TARGETARCH - Architecture from --platform, e.g. arm64
ARG TARGETOS
ARG TARGETARCH
ARG LOCAL_CONFIG_PATH="./images/example/mysql_snapshot_sample.yaml"
ARG MODULE_NAME="ape-dts"
ENV CONFIG_PATH=config_example 

COPY ${LOCAL_CONFIG_PATH} ${CONFIG_PATH}
COPY log4rs.yaml log4rs.yaml
COPY ./images/${TARGETARCH}/${MODULE_NAME} ape-dts

CMD [ "sh", "-c", "/ape-dts ${CONFIG_PATH}" ]
