pub mod base_checker;
pub mod base_sinker;
pub mod base_struct_sinker;
pub mod clickhouse;
#[cfg(feature = "duckdb_connector")]
pub mod duckdb;
pub mod dummy_sinker;
pub mod foxlake;
pub mod kafka;
pub mod mongo;
pub mod mysql;
pub mod pg;
pub mod redis;
pub mod sql_sinker;
pub mod starrocks;
