FROM rust:1.67.0 as builder

ARG GIT_TOKEN
ARG GIT_BRANCH

RUN apt-get update && apt-get install -y git 
RUN if [ -n "${GIT_BRANCH}" ]; \
    then git clone -b ${GIT_BRANCH} https://${GIT_TOKEN}@github.com/apecloud/ape-dts.git; \
    else git clone https://${GIT_TOKEN}@github.com/apecloud/ape-dts.git; \
    fi
RUN git clone https://${GIT_TOKEN}@github.com/apecloud/mysql-binlog-connector-rust.git
RUN sed -i '/mysql-binlog-connector-rust/s/^mysql-binlog-connector-rust.*$/mysql-binlog-connector-rust = \{ path = "\/mysql-binlog-connector-rust" \}/g' /ape-dts/Cargo.toml \
    && cd /ape-dts \
    && cargo build --release   

CMD [ "sh", "-c", "sleep 1d" ]
